branches:
  only:
    - master

sudo: false

os:
  - linux

language: generic

env:
- PY=2.7 MPI=1
- PY=3.4 MPI=1
- PY=2.7 MPI=
- PY=3.4 MPI=


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

notifications:
  email: false
  slack:
    on_success: never
    secure: c8xi/sAb5QJPR7CrFPdL/sXOhPFdyR3E9lv9Z2h2CxGQWINyRN6Xj7/rF6bW0PfINvqFAHL4+iPM+0bmM0+Av9AW3Dg2fXZuN3XueMwNTFnnpO2g1NKJ44cFsGXCPytLTvg+zZqxzR+Fz13DcrdHQEhfSKcuZ3akbp3OIAdAYmpaiqZPz9NBX3M7LvDOnWa9TNxznltR1LHtdP3RGOm/xput0dvGuY8zJSTYCxusnZNYBz5IQuNSoyBfqOFztLl6MGcqT5+/cE+T2AXEPLOKGJXahOdk3d/UXEb/vRGc19oPU/ORZZvde7IuAK1GJhjXPUhgmqLIlFTRlOpLBcllUW8asKHeRIHOvNbzMrYKngq7JLe97cshabNvvXH3MYG5HJKkqOWD6boe5JXxpkruE4oF3JCIgSs888YWC4bdAvOmxU8rxtBp4N5S+PXgqzOPDu10klcNOfSI3DYP/4tbZ25/RCrmwJbj6H1+Foi+oxkjDQnxabg6rUcB0ILykue5bogSKSk6HsIp0jU2zwpv7b5w4r1pMgZD6L+mlR5N16X4qFwQAbxWaxQYADywzbWRshEPkHCaMriHCWi3IOU/ESrbKfCT9h66uGMrkv/5qEHoYFn3TZaLHSTOKRnT5SYHd9BiKmBBUKiOxI1Gf6tyxeG/ndowWFQrz8HLESFNRO4=

before_install:
- OS=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "MacOSX"; else echo "Linux"; fi)
- if [ "$OS" = "MacOSX" ] && [ "$MPI" ]; then brew install openmpi; fi
- wget "https://repo.continuum.io/miniconda/Miniconda-latest-$OS-x86_64.sh" -O miniconda.sh
- chmod +x miniconda.sh
- if [ "$OS" = "Linux" ]; then
    ./miniconda.sh -b  -p /home/travis/miniconda;
  fi
- if [ "$OS" = "MacOSX" ]; then
    ./miniconda.sh -b  -p /Users/travis/miniconda;
  fi
- PATHPREFIX=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "/Users/travis/miniconda/bin"; else echo "/home/travis/miniconda/bin"; fi)
- export PATH=$PATHPREFIX:$PATH
- export OPENMDAO_TEST_DOCS=1

install:
- conda install --yes python=$PY numpy scipy nose sphinx==1.5 mock swig
- if [ "$OS" = "Linux" ]; then
    if [ "$PY" = "2.7" ]; then
        pip install https://openmdao.org/dists/pyoptsparse-1.0.0-cp27-none-linux_x86_64.whl;
    elif [ "$PY" = "3.4" ]; then
        pip install https://openmdao.org/dists/pyoptsparse-1.0.0-py3-none-linux_x86_64.whl;
    fi
  fi
- if [ "$OS" = "MacOSX" ]; then
    if [ "$PY" = "2.7" ]; then
        pip install https://openmdao.org/dists/pyoptsparse-1.0.0-py2-none-macosx_10_5_x86_64.whl;
    elif [ "$PY" = "3.4" ]; then
        pip install https://openmdao.org/dists/pyoptsparse-1.0.0-cp34-none-macosx_10_5_x86_64.whl;
    fi
  fi
- if [ "$MPI" ]; then
    pip install mpi4py;
    pip install git+https://bitbucket.org/petsc/petsc4py@3.7.0;
  fi
- pip install redbaron
- pip install git+https://github.com/OpenMDAO/testflo.git
- pip install -e .

script:
- testflo . -m "ptest*"
- testflo .
#after tests, need to cd down so that conf.py can be found for doc build
- cd openmdao/docs
- make all
